apiVersion: v1
kind: Service
metadata:
  name: api-payment-service
spec:
  selector:
    app: api-payment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31001
  type: LoadBalancer
